config/routes.rb
Rails.application.routes.draw do
  root 'homes#show'
  resources :users, only: [:create, :new, :show]
  resources :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    validates :qname, presence: true
    validates :option1, presence: true
    validates :option2, presence: true
    validates :option3, presence: true
    validates :option4, presence: true
    validates :correct_ans, presence: true
    validates :time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :contact, presence: true
    attribute :score, default: 0 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    before_action :setQuestions, only: [:index]

    def index
    end

    def show
        @question = Question.find(params[:id])
    end

    def new
        @question = Question.new
    end

    def create
        @question = Question.new(params.require(:question).permit(:qname,:option1,:option2,:option3,:option4,:correct_ans,:time))
        if @question.save
            flash[:notice] = "Question successfully created!"
            render 'new'
        else
            flash[:notice] = "Error occured in creating question!"
            render 'new'
        end
    end

    private
    def setQuestions
        @questions = Question.all.sample(10)
        cookies[:questions] = @questions
        cookies[:index] = 0
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :contact))
    if @user.save
      cookies[:score] = 0
      redirect_to questions_url
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gemsessence</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="header-dashboard">
    <h1>Welcome to Gemsessence</h1>
    <div class="links">
      <%= link_to 'Enroll & Start',  new_user_path %>
      <%= link_to 'Admin', new_question_path %>
    </div>
  </div>
  <% flash.each do |name,msg| %>
    <%= msg %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: @question, local: true, class: "q-form") do |f| %>
    <div class="input-field">
        <%= f.label :qname %>
        <br>
        <%= f.text_field :qname, placeholder: "Type in the question" %>
    </div>
    <div class="input-field">
        <%= f.label :option1, class: 'label' %>
        <br>
        <%= f.text_field :option1, placeholder: "Type in the option 1" %>
    </div>
    <div class="input-field">
        <%= f.label :option2, class: 'label' %>
        <br>
        <%= f.text_field :option2, placeholder: "Type in the option 2" %>
    </div>
    <div class="input-field">
        <%= f.label :option3, class: 'label' %>
        <br>
        <%= f.text_field :option3, placeholder: "Type in the option 3" %>
    </div>
    <div class="input-field">
        <%= f.label :option4, class: 'label' %>
        <br>
        <%= f.text_field :option4, placeholder: "Type in the option 4" %>
    </div>
    <div class="input-field">
        <%= f.label :correct_ans, class: 'label' %>
        <br>
        <%= f.text_field :correct_ans, placeholder: "Type in the correct answer" %>
    </div>
    <div class="input-field">
        <%= f.label :time, class: 'label' %>
        <br>
        <%= f.time_field :time, placeholder: "Type in the time" %>
    </div>
    <div class="buttons">
        <%= f.submit class: "start-test" %>
        <%= link_to 'Cancel', root_path, class: "cancel-test" %>
    </div>    
     
<% end %>

app/views/questions/index.html.erb
<div class="questions">
    <%= link_to 'Begin', @questions.first, class: "start-test" %>
    <% time = 0.seconds %>
    <% @questions.each do |q| %>
        <% time =  q.time.min.to_i + time.to_i %>
    <% end %>
    <span class="total-time"><%= "Total time : " + time.to_s %></span> 
    <% @questions.each_with_index do |question,index| %>
        <div class="question-time">
            <%= link_to "Q." + (index+1).to_s + " " + question.qname, question, class: 'question' %>
            <p class="time-index"> <%= question.time.to_formatted_s(:time) %> </p>
        </div>
    <% end %>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="question-time">
    <p class="question"><%= @question.qname %></p>
    <p class="time-index"> <%= @question.time.to_formatted_s(:time) %> </p>
</div>
<div class="options">
    <div class="option">
        <span><%= @question.option1 %></span>
        <span class="rounded-circle" data-ans="A" data-ca="<%= @question.correct_ans == "A" %>">
            <span class="inner-circle"></span>
        </span>
    </div>
    <div class="option">
        <span><%= @question.option2 %></span>
        <span class="rounded-circle" data-ans="B" data-ca="<%= @question.correct_ans == "B" %>">
            <span class="inner-circle"></span>
        </span>
    </div>
    <div class="option">
        <span><%= @question.option3 %></span>
        <span class="rounded-circle" data-ans="C" data-ca="<%= @question.correct_ans == "C" %>">
            <span class="inner-circle"></span>
        </span>
    </div>
    <div class="option">
        <span><%= @question.option4 %></span>
        <span class="rounded-circle" data-ans="D" data-ca="<%= @question.correct_ans == "D" %>">
            <span class="inner-circle"></span>
        </span>
    </div>
</div>
<% cookies[:index] = cookies[:index].to_i + 1  %>
<%= link_to 'Next', root_path , class: 'next-q' %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <div class="input-field">
        <%= f.label :name %>
        <br>
        <%= f.text_field :name, placeholder: "Your Full Name" %>
    </div>
    <div class="input-field">
        <%= f.label :email, class: 'label' %>
        <br>
        <%= f.text_field :email, placeholder: "Your Email Id" %>
    </div>
    <div class="input-field">
        <%= f.label :contact, class: 'label' %>
        <br>
        <%= f.text_field :contact, placeholder: "Your Phone Number" %>
    </div>
    <div class="buttons">    
        <%= f.submit "Start", class: "start-test" %>
        <%= link_to 'Cancel', root_path, class: "cancel-test" %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1 class="form-heading"> Enroll and Give the test </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="score-card">
    <h1>Hello, <%= @user.name %> </h1>
    <h2>Your score is <%= cookies[:score] %> </h2>
</div>